apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:7003
  CLUSTER_ID: Local
  SERVICE_ID: Orleans-Tournament
  BUILD_VERSION: 0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-identity-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:7004
  BUILD_VERSION: 0.0.1
