apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      tier: backend
      role: client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        tier: backend
        role: client
    spec:
      containers:
      - name: ot-api
        image: ot-api:local
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: api-config
        env:
        - name: POSTGRES_CONNECTION
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: value
        - name: JWT_ISSUER_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-issuer-key
              key: value
        lifecycle:
          preStop:
            httpGet:
              path: "leave"
              port: 80
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-identity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      tier: backend
      role: identity
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        tier: backend
        role: identity
    spec:
      containers:
      - name: ot-api-identity
        image: ot-api-identity:local
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: api-identity-config
        env:
        - name: POSTGRES_CONNECTION
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: value
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-issuer-key
              key: value
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
