apiVersion: v1
kind: ConfigMap
metadata:
  name: silo-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:7001
  CLUSTER_ID: Local
  SERVICE_ID: Orleans-Tournament
  SILO_PORT: "11111"
  GATEWAY_PORT: "30000"
  BUILD_VERSION: 0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: silo-dashboard-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:7002
  CLUSTER_ID: Local
  SERVICE_ID: Orleans-Tournament
  BUILD_VERSION: 0.0.1
