kind: Service
apiVersion: v1
metadata:
  name: silo-service
spec:
  selector:
    app: silo
    tier: backend
    role: host
  ports:
  - name: http
    port: 80
    targetPort: 80 #internal port
    nodePort: 30701 #external port
  - name: silo
    port: 30710
    targetPort: 30710 #internal port
    nodePort: 30710 #external port
  - name: gateway
    port: 30711
    targetPort: 30711 #internal port
    nodePort: 30711 #external port
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: silo-dashboard-service
spec:
  selector:
    app: silo
    tier: backend
    role: dashboard
  ports:
  - name: http
    port: 80
    targetPort: 80 #internal port
    nodePort: 30702 #external port
  type: NodePort
